name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: manavmalavia18
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=%2300e5ff&color_dots=%23060b14,%230b2233,%230f3a52,%23157a9e,%2300e5ff
      - name: push snake svgs to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
